use midnight_proofs::transcript::Blake2b256;

use crate::{
    MembershipDigest, StmResult,
    circuits::halo2_ivc::keys::RecursiveCircuitVerifyingKey,
    proof_system::{
        IvcRollingState,
        halo2_ivc_snark::proof::{IvcChainStepBundle, IvcProof},
    },
};

/// A trait that represents the functions needed by a recursive SNARK to generate
/// the next step of the chain of certificates.
#[cfg_attr(test, mockall::automock)]
pub(crate) trait IvcChainProver<D: MembershipDigest> {
    /// Returns the recursive SNARK verification key used to verify the IvcProof
    /// generated by advance_chain().
    fn verifying_key(&self) -> &RecursiveCircuitVerifyingKey;
    /// Function that advances the chain proof by taking one step, generating a proof
    /// that certifies all the certificates back to the genesis certificate.
    fn advance_chain(
        &mut self,
        step_bundle: IvcChainStepBundle<D>,
    ) -> StmResult<(IvcProof<Blake2b256>, Option<IvcRollingState>)>;
}
