use std::fmt::Debug;

use midnight_proofs::transcript::Blake2b256;

use crate::{
    AggregateVerificationKeyForSnark, AncillaryProofInput, MembershipDigest, StmResult,
    circuits::halo2_ivc::keys::RecursiveCircuitVerifyingKey,
    proof_system::{
        IvcRollingState,
        halo2_ivc_snark::proof::{IvcChainStepBundle, IvcProof},
    },
};

/// A trait that represents the functions needed by a recursive SNARK to generate
/// the next step of the chain of certificates.
#[cfg_attr(test, mockall::automock)]
pub(crate) trait IvcChainProver<D: MembershipDigest> {
    /// Returns the recursive SNARK verification key used to verify the IvcProof
    /// generated by advance_chain().
    fn verifying_key(&self) -> &RecursiveCircuitVerifyingKey;
    /// Function that advances the chain proof by taking one step, generating a proof
    /// that certifies all the certificates back to the genesis certificate.
    fn advance_chain(
        &mut self,
        step_bundle: IvcChainStepBundle<D>,
    ) -> StmResult<(IvcProof<Blake2b256>, Option<IvcRollingState>)>;
}

/// A trait that represents the off-circuit (CPU-side) validation checks run against an incoming
/// certificate and its ancillary data before the recursive SNARK proving path begins. Rejecting
/// an invalid request here avoids paying for certificate/IVC proof generation on a request that
/// could never verify.
#[cfg_attr(test, mockall::automock)]
pub(crate) trait IvcOffCircuitChecker<D: MembershipDigest>: Debug {
    /// Runs off-circuit checks that mirror what the recursive circuit itself enforces in-circuit,
    /// validating the caller-supplied certificate message, ancillary data, and aggregate
    /// verification key before any of it is trusted for proof generation.
    ///
    /// Returns `Ok(())` when every check passes, otherwise the first failing check's error.
    fn off_circuit_check(
        &self,
        msg: &[u8],
        aggregate_verification_key: &AggregateVerificationKeyForSnark<D>,
        ancillary_input: &AncillaryProofInput,
    ) -> StmResult<()>;
}
