[package]
name = "mithril-client-wasm"
version = "0.10.12"
description = "Mithril client WASM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
categories = ["cryptography"]

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[lib]
crate-type = ["cdylib"]

[features]
default = ["rustls"]
rustls = ["mithril-client/rustls"]
test-node = []
snark = ["mithril-client/snark"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
js-sys = "0.3.106"
mithril-client = { path = "../mithril-client", default-features = false, features = ["unstable"] }
serde = { workspace = true }
serde-wasm-bindgen = "0.6.5"
serde_json = { workspace = true }
wasm-bindgen = "0.2.129"
wasm-bindgen-futures = "0.4.79"
web-sys = { version = "0.3.106", features = [
    "BroadcastChannel",
    "DomException",
    "IdbDatabase",
    "IdbFactory",
    "IdbIndex",
    "IdbKeyRange",
    "IdbObjectStore",
    "IdbObjectStoreParameters",
    "IdbOpenDbRequest",
    "IdbRequest",
    "IdbTransaction",
    "IdbTransactionMode",
    "IdbVersionChangeEvent",
] }

[target.'cfg(all(target_family = "wasm"))'.dependencies]
# This getrandom version is required without the snark feature, and it can be removed once the snark feature is enabled.
getrandom = { version = "0.2", features = ["js"] }
# This getrandom version is required with the snark feature (because of Midnight ZK dependency)
getrandom-snark = { package = "getrandom", version = "0.4.3", features = ["wasm_js"] }

[build-dependencies]
mithril-build-script = { path = "../internal/mithril-build-script" }

[dev-dependencies]
mithril-common = { path = "../mithril-common", default-features = false }
wasm-bindgen-test = "0.3.79"
