[package]
name = "mithril-doc-derive"
version = "0.1.26"
description = "An internal macro to support documentation generation."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true

[features]
default = []

[dependencies]
quote = "1.0.47"
syn = { version = "3.0.6", features = ["full"] }
