use crate::{
    MembershipDigest, SingleSignature, SnarkProof, StmResult,
    circuits::halo2::keys::NonRecursiveCircuitVerifyingKey, proof_system::SnarkClerk,
};

/// A trait that represents the functions a non-recursive SNARK prover
/// needs in order to aggregate signatures
#[cfg_attr(test, mockall::automock)]
pub(crate) trait SnarkAggregateSignatureProver<D: MembershipDigest> {
    /// Returns the non-recursive SNARK verifying key used to verify
    /// the SnarkProof generated by aggregate_signatures().
    fn verifying_key(&self) -> &NonRecursiveCircuitVerifyingKey;
    /// A function that aggregates the input signatures into a succinct proof that can be verified
    /// using the verifying key returned by verifying_key().
    fn aggregate_signatures(
        &mut self,
        clerk: &SnarkClerk,
        signatures: &[SingleSignature],
        message: &[u8],
    ) -> StmResult<SnarkProof<D>>;
}
