use std::{marker::PhantomData, sync::Arc};

use anyhow::Context;
use midnight_circuits::hash::poseidon::PoseidonState;
use midnight_curves::Bls12;
use midnight_proofs::poly::kzg::{msm::DualMSM, params::ParamsVerifierKZG};
use midnight_zk_stdlib::{self as zk};
#[cfg(test)]
use rand_chacha::ChaCha20Rng;
#[cfg(test)]
use rand_core::SeedableRng;
use rand_core::{CryptoRng, RngCore};
use serde::{Deserialize, Serialize};

use crate::{
    MembershipDigest, Parameters, SingleSignature, StmResult,
    circuits::{
        halo2::{circuit::CertificateCircuit, types::CircuitBase},
        halo2_ivc::{
            certificate_proof::verify_and_prepare_accumulator, types::CertificateProofBytes,
        },
    },
    codec,
    proof_system::{
        AggregateVerificationKeyForSnark,
        halo2_snark::{
            SnarkProofError, build_snark_message, interface::SnarkAggregateSignatureProver,
            prover_input::SnarkProverInput,
        },
    },
};

use super::{SnarkClerk, SnarkProverSetup, SnarkVerifierData};
use crate::circuits::halo2::keys::NonRecursiveCircuitVerifyingKey;

/// `SnarkProof` contains a proof generated by the certificate circuit represented as a vector of
/// bytes. It can be verified using verifier parameters derived from the srs, the circuit verification key
/// and the public inputs which are all public values
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnarkProof<D: MembershipDigest> {
    /// Raw proof bytes produced by the SNARK prover.
    #[serde(with = "serde_bytes")]
    circuit_proof: Vec<u8>,
    // The protocol parameters
    // Note: this field is temporary and will be removed once the circuit setup is stable
    params: Parameters,
    /// The maximum Merkle tree depth
    // Note: this field is temporary and will be removed once the circuit setup is stable
    merkle_tree_depth: u32,
    /// Phantom data
    #[serde(skip)]
    phantom: PhantomData<D>,
}

impl<D: MembershipDigest> SnarkProof<D> {
    /// Builds a SnarkProof from the raw proof bytes, protocol parameters and Merkle tree depth.
    ///
    /// The certificate verification key is not stored on the proof; it is carried in the
    /// certificate's ancillary verifier data and supplied at verification time, so this
    /// constructor performs no key generation.
    pub fn new(circuit_proof: Vec<u8>, params: Parameters, merkle_tree_depth: u32) -> Self {
        Self {
            circuit_proof,
            params,
            merkle_tree_depth,
            phantom: PhantomData,
        }
    }

    pub(crate) fn into_circuit_proof_bytes(self) -> CertificateProofBytes {
        CertificateProofBytes::from_certificate_circuit_proof_bytes(self.circuit_proof)
    }

    /// Verify a SNARK proof given a message, an aggregate verification key for snark,
    /// the SNARK verifier data (carrying the certificate circuit verification key) and the KZG
    /// verifier parameters.
    ///
    /// This proof verifies that there exists a witness such that:
    /// * each signatures in the witness is valid for the given message
    /// * each signatures has a winning lottery index
    /// * each leaf in the witness has a valid merkle path
    /// * each lottery index is unique and fits the parameters
    /// * enough lottery index are valid to meet the parameters requirements
    ///
    pub fn verify(
        &self,
        message: &[u8],
        aggregate_verification_key_for_snark: &AggregateVerificationKeyForSnark<D>,
        snark_verifier_data: &SnarkVerifierData,
        verifier_params: &ParamsVerifierKZG<Bls12>,
    ) -> StmResult<()> {
        let merkle_tree_commitment_bytes =
            &aggregate_verification_key_for_snark.get_merkle_tree_commitment().root;
        let proof_message = build_snark_message(merkle_tree_commitment_bytes, message)?;
        let proof_instance = (proof_message[0].into(), proof_message[1].into());

        let verify_result = zk::verify::<CertificateCircuit, PoseidonState<CircuitBase>>(
            verifier_params,
            snark_verifier_data
                .certificate_circuit_verification_key()
                .midnight_vk(),
            &proof_instance,
            None,
            &self.circuit_proof,
        );

        verify_result.map_err(|_| SnarkProofError::VerifyProofFail.into())
    }

    /// Runs the off-circuit SNARK verifier and returns the verifier's intermediate
    /// `DualMSM`.
    ///
    /// The public inputs are reconstructed from `message` and the Merkle tree commitment
    /// inside `aggregate_verification_key_for_snark`; the proof is then checked
    /// against the certificate verifying key under the Poseidon transcript.
    ///
    /// Functionally equivalent to [`Self::verify`] except for the return shape:
    /// [`Self::verify`] consumes the verifier's intermediate accumulator in its
    /// pairing check and yields `()`, while this method pairing-checks a clone and
    /// hands back the original `DualMSM` on success. The returned accumulator is
    /// the off-circuit twin of the one an in-circuit IVC verifier gadget would
    /// compute on the same proof, so it can be wrapped into a certificate
    /// accumulator for recursive aggregation.
    pub(crate) fn prepare_and_check(
        &self,
        message: &[u8],
        aggregate_verification_key_for_snark: &AggregateVerificationKeyForSnark<D>,
        circuit_verification_key: &NonRecursiveCircuitVerifyingKey,
        verifier_params: &ParamsVerifierKZG<Bls12>,
    ) -> StmResult<DualMSM<Bls12>> {
        let merkle_tree_commitment_bytes =
            &aggregate_verification_key_for_snark.get_merkle_tree_commitment().root;
        let proof_message = build_snark_message(merkle_tree_commitment_bytes, message)?;
        let public_inputs: Vec<CircuitBase> =
            vec![proof_message[0].into(), proof_message[1].into()];

        verify_and_prepare_accumulator(
            &self.circuit_proof,
            &public_inputs,
            circuit_verification_key.as_ref(),
            verifier_params,
        )
    }

    /// Converts a SnarkProof to CBOR bytes with a version prefix.
    pub fn to_bytes(&self) -> StmResult<Vec<u8>> {
        codec::to_cbor_bytes(self)
    }

    /// Deserialise a proof from versioned CBOR bytes.
    ///
    /// The certificate verification key is no longer part of the proof; a non-versioned (legacy
    /// fixed-offset) proof is rejected.
    pub fn from_bytes(bytes: &[u8]) -> StmResult<Self> {
        if codec::has_cbor_v1_prefix(bytes) {
            codec::from_cbor_bytes(&bytes[1..])
        } else {
            Err(SnarkProofError::SerializationError.into())
        }
    }
}

/// Holds the pre-computed SNARK setup and exposes proof generation.
///
/// The type parameter `R` selects the randomness source used during proof generation.
/// Use `new_non_deterministic` for production (`OsRng`) and `try_new_deterministic` for
/// reproducible tests.
pub struct SnarkProver<R: RngCore + CryptoRng> {
    setup: Arc<SnarkProverSetup>,
    rng: R,
}

impl SnarkProver<rand_core::OsRng> {
    /// Create a new prover with a non-deterministic randomness source (`OsRng`) over `setup`.
    ///
    /// This is the constructor intended for production use. The setup is provided by the factory,
    /// which owns whether it is reused across aggregations.
    pub fn new_non_deterministic(setup: Arc<SnarkProverSetup>) -> Self {
        Self {
            setup,
            rng: rand_core::OsRng,
        }
    }
}

#[cfg(test)]
impl SnarkProver<ChaCha20Rng> {
    /// Create a new prover with a deterministic randomness source seeded from `seed` (for tests only).
    pub fn try_new_deterministic(seed: [u8; 32], setup: SnarkProverSetup) -> StmResult<Self> {
        Ok(Self {
            setup: Arc::new(setup),
            rng: ChaCha20Rng::from_seed(seed),
        })
    }

    /// KZG verifier parameters derived from the prover's SRS, to verify the proofs it produces. (for tests only).
    pub fn verifier_params(&self) -> ParamsVerifierKZG<Bls12> {
        self.setup.srs.verifier_params()
    }
}

impl<D: MembershipDigest, R: RngCore + CryptoRng> SnarkAggregateSignatureProver<D>
    for SnarkProver<R>
{
    /// Returns the certificate circuit verification key derived by this prover's setup.
    ///
    /// The clerk clones this before proving so the certificate's ancillary verifier data and the
    /// proof provably originate from the same setup.
    fn verifying_key(&self) -> &NonRecursiveCircuitVerifyingKey {
        &self.setup.verification_key
    }

    /// Aggregate a set of single signatures into a SNARK proof.
    ///
    /// Prepares the prover input (public instance and per-index witness) from the collected
    /// single signatures, then runs the SNARK prover.
    ///
    /// Returns an error if fewer than `k` valid signatures are available or if proof generation fails.
    fn aggregate_signatures(
        &mut self,
        clerk: &SnarkClerk,
        signatures: &[SingleSignature],
        message: &[u8],
    ) -> StmResult<SnarkProof<D>> {
        let snark_prover_input =
            SnarkProverInput::prepare_prover_input::<D>(clerk, signatures, message)
                .with_context(|| "Failed to prepare SNARK prover input")?;
        let instance = snark_prover_input.get_instance();
        let witness = snark_prover_input.into_witness();

        let circuit_proof = zk::prove::<CertificateCircuit, PoseidonState<CircuitBase>>(
            &self.setup.srs,
            self.setup.proving_key.midnight_pk(),
            &self.setup.circuit,
            &instance,
            witness,
            &mut self.rng,
        )
        .with_context(|| "SNARK proof generation failed")?;

        Ok(SnarkProof {
            circuit_proof,
            params: clerk.parameters,
            merkle_tree_depth: clerk
                .closed_key_registration
                .number_of_registered_parties()
                .next_power_of_two()
                .trailing_zeros(),
            phantom: PhantomData,
        })
    }
}

#[cfg(feature = "snark")]
#[cfg(test)]
mod tests {

    use rand_chacha::ChaCha20Rng;
    use rand_core::{OsRng, RngCore, SeedableRng};

    use crate::{
        Initializer, KeyRegistration, MithrilMembershipDigest, Signer, SingleSignature,
        proof_system::{
            SnarkClerk,
            halo2_snark::{
                MERKLE_TREE_DEPTH_FOR_SNARK, SnarkProverSetup, SnarkVerifierData,
                proof::{SnarkAggregateSignatureProver, SnarkProof},
                prover_input::SnarkProverInput,
            },
        },
    };

    use super::{Parameters, SnarkProver};

    type D = MithrilMembershipDigest;

    fn setup_signers_and_clerk(
        params: Parameters,
        nparties: usize,
        rng: &mut ChaCha20Rng,
    ) -> (Vec<Signer<D>>, SnarkClerk) {
        let mut key_reg = KeyRegistration::initialize();
        let mut initializers = Vec::with_capacity(nparties);

        for _ in 0..nparties {
            let init = Initializer::new(params, 1, rng);
            key_reg.register_by_entry(&init.clone().try_into().unwrap()).unwrap();
            initializers.push(init);
        }

        let closed_reg = key_reg.close_registration(&params).unwrap();
        let signers: Vec<Signer<D>> = initializers
            .into_iter()
            .map(|init| init.try_create_signer::<D>(&closed_reg).unwrap())
            .collect();

        let clerk = SnarkClerk::new_clerk_from_signer(&signers[0]);
        (signers, clerk)
    }

    fn collect_signatures(signers: &[Signer<D>], message: &[u8]) -> Vec<SingleSignature> {
        signers
            .iter()
            .filter_map(|signer| signer.create_single_signature(message).ok())
            .collect()
    }

    fn snark_verifier_data(prover: &SnarkProver<ChaCha20Rng>) -> SnarkVerifierData {
        SnarkVerifierData::new(SnarkAggregateSignatureProver::<D>::verifying_key(prover).clone())
    }

    fn snark_verifier_data_non_deterministic(prover: &SnarkProver<OsRng>) -> SnarkVerifierData {
        SnarkVerifierData::new(SnarkAggregateSignatureProver::<D>::verifying_key(prover).clone())
    }

    fn create_prover(params: Parameters, seed: [u8; 32]) -> SnarkProver<ChaCha20Rng> {
        // Derives the key through `SnarkProverSetup::build_for_test`, which keys the shared cache by
        // the parameters, depth and unsafe seed (not the SRS degree, since keygen downsizes to the
        // circuit's degree), so the certificate key is computed once and reused across tests.
        let snark_setup =
            SnarkProverSetup::build_for_test(&params, MERKLE_TREE_DEPTH_FOR_SNARK).unwrap();

        SnarkProver::try_new_deterministic(seed, snark_setup).unwrap()
    }

    mod slow {
        use crate::{StmResult, proof_system::AggregateVerificationKeyForSnark};

        use super::*;

        #[test]
        fn fails_with_empty_signatures() {
            let mut rng = ChaCha20Rng::from_seed([2u8; 32]);
            let params = Parameters {
                m: 200,
                k: 3,
                phi_f: 0.8,
            };
            let nparties = 5;

            let (_, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
            let mut prover = create_prover(params, [2u8; 32]);

            let result: StmResult<SnarkProof<D>> =
                prover.aggregate_signatures(&clerk, &[], &[3u8; 32]);
            assert!(result.is_err(), "Expected failure with empty signatures");
        }

        #[test]
        fn fails_with_insufficient_signatures() {
            let mut rng = ChaCha20Rng::from_seed([1u8; 32]);
            let params = Parameters {
                m: 20,
                k: 3,
                phi_f: 0.1,
            };
            let nparties = 4;
            let message = [2u8; 32];

            let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
            let signatures = collect_signatures(&signers, &message);
            let mut prover = create_prover(params, [1u8; 32]);

            let result: StmResult<SnarkProof<D>> =
                prover.aggregate_signatures(&clerk, &signatures, &message);
            assert!(
                result.is_err(),
                "Expected failure due to insufficient signatures"
            );
        }

        #[test]
        fn produces_valid_snark_proof() {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let params = Parameters {
                m: 200,
                k: 5,
                phi_f: 0.8,
            };
            let nparties = 10;
            let message = [1u8; 32];

            let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
            let signatures = collect_signatures(&signers, &message);
            let mut prover = create_prover(params, [0u8; 32]);

            let result: StmResult<SnarkProof<MithrilMembershipDigest>> =
                prover.aggregate_signatures(&clerk, &signatures, &message);
            assert!(
                result.is_ok(),
                "Expected proof creation to succeed, got: {result:?}"
            );

            let proof = result.unwrap();
            assert!(
                !proof.circuit_proof.is_empty(),
                "Proof bytes should not be empty"
            );

            // Every other `prepare_and_check` test runs on the committed golden proof, so this is
            // the only coverage of it against a freshly produced one.
            let avk = clerk.compute_aggregate_verification_key_for_snark();
            let dual_msm = proof
                .prepare_and_check(
                    &message,
                    &avk,
                    SnarkAggregateSignatureProver::<D>::verifying_key(&prover),
                    &prover.verifier_params(),
                )
                .expect("prepare_and_check should succeed on a freshly produced proof");
            assert!(dual_msm.check(&prover.verifier_params()));
        }

        #[test]
        fn valid_snark_proof_with_different_path_length() {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let params = Parameters {
                m: 200,
                k: 3,
                phi_f: 0.8,
            };
            let nparties = 10;
            let message = [1u8; 32];
            let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
            let signatures = collect_signatures(&signers, &message);
            let avk = clerk.compute_aggregate_verification_key_for_snark::<D>();

            let current_merkle_tree_depth = clerk
                .closed_key_registration
                .number_of_registered_parties()
                .next_power_of_two()
                .trailing_zeros();
            let mut prover = create_prover(params, [0u8; 32]);

            let prover_prep =
                SnarkProverInput::prepare_prover_input::<D>(&clerk, &signatures, &message).unwrap();

            let path_length =
                prover_prep.into_witness().first().unwrap().merkle_path.siblings.len();

            assert!(path_length >= current_merkle_tree_depth as usize);

            let snark_proof = prover.aggregate_signatures(&clerk, &signatures, &message).unwrap();
            let result = snark_proof.verify(
                message.as_slice(),
                &avk,
                &snark_verifier_data(&prover),
                &prover.verifier_params(),
            );

            assert!(result.is_ok());
            snark_proof
                .verify(
                    message.as_slice(),
                    &avk,
                    &snark_verifier_data(&prover),
                    &prover.verifier_params(),
                )
                .expect("SNARK proof verification should succeed");
        }

        #[test]
        fn different_parameters_prove_and_verify_fails() {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let params = Parameters {
                m: 100,
                k: 5,
                phi_f: 0.8,
            };
            let forged_params = Parameters { m: 3000, ..params };
            assert_ne!(params, forged_params);
            let nparties = 10;
            let merkle_tree_depth = (nparties as u32).next_power_of_two().trailing_zeros();
            let message = [1u8; 32];
            let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
            let signatures = collect_signatures(&signers, &message);
            let avk: AggregateVerificationKeyForSnark<MithrilMembershipDigest> =
                clerk.compute_aggregate_verification_key_for_snark();

            let mut forged_prover = create_prover(forged_params, [0u8; 32]);

            let forged_snark_proof: SnarkProof<D> = forged_prover
                .aggregate_signatures(&clerk, &signatures, &message)
                .unwrap();

            let snark_proof =
                SnarkProof::new(forged_snark_proof.circuit_proof, params, merkle_tree_depth);
            // Verify the forged-parameter proof against the honest-parameter verifying key.
            let honest_prover = create_prover(params, [0u8; 32]);
            let result = snark_proof.verify(
                message.as_slice(),
                &avk,
                &snark_verifier_data(&honest_prover),
                &honest_prover.verifier_params(),
            );

            assert!(result.is_err());
        }

        #[test]
        fn non_deterministic_proofs_verify() {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let params = Parameters {
                m: 100,
                k: 5,
                phi_f: 0.8,
            };
            let nparties = 10;
            let message = [1u8; 32];
            let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
            let signatures = collect_signatures(&signers, &message);
            let avk = clerk.compute_aggregate_verification_key_for_snark::<D>();

            let mut prover_1 = create_prover(params, [0u8; 32]);

            let snark_proof_1 =
                prover_1.aggregate_signatures(&clerk, &signatures, &message).unwrap();
            let snark_proof_2 =
                prover_1.aggregate_signatures(&clerk, &signatures, &message).unwrap();

            assert!(
                snark_proof_1
                    .verify(
                        &message,
                        &avk,
                        &snark_verifier_data(&prover_1),
                        &prover_1.verifier_params()
                    )
                    .is_ok()
            );
            assert!(
                snark_proof_2
                    .verify(
                        &message,
                        &avk,
                        &snark_verifier_data(&prover_1),
                        &prover_1.verifier_params()
                    )
                    .is_ok()
            );
            assert_ne!(
                snark_proof_1.circuit_proof, snark_proof_2.circuit_proof,
                "The two proofs are different but both verify."
            );
        }
    }

    #[test]
    fn into_circuit_proof_bytes_carries_the_proof_bytes_and_drops_params() {
        // Bytes `0..64`, pairwise distinct: an all-constant fixture makes the
        // "carried across unchanged" assertion vacuous.
        let proof_bytes: Vec<u8> = (0..64).map(|i| i as u8).collect();
        let proof = SnarkProof::<D>::new(
            proof_bytes.clone(),
            Parameters {
                k: 1,
                m: 10,
                phi_f: 0.9,
            },
            MERKLE_TREE_DEPTH_FOR_SNARK,
        );

        let circuit_proof_bytes = proof.into_circuit_proof_bytes();

        assert_eq!(
            circuit_proof_bytes.as_bytes(),
            proof_bytes.as_slice(),
            "the circuit proof bytes must be the prover output verbatim"
        );
    }

    mod golden {
        use std::sync::Arc;

        use ff::PrimeField;
        use midnight_curves::Fq as JubjubBase;
        use num_bigint::BigUint;
        use num_traits::Num;

        use crate::{
            AggregateSignature, AggregateVerificationKey, AncillaryVerifierData, Clerk,
            circuits::{
                halo2::{
                    NON_RECURSIVE_CIRCUIT_VERIFICATION_KEY_FOR_PRODUCTION,
                    keys::NonRecursiveCircuitVerifyingKey,
                },
                trusted_setup::TrustedSetupProvider,
            },
            codec::TryFromBytes,
            proof_system::{AggregateVerificationKeyForSnark, SnarkVerifierSetup},
        };

        use super::*;

        const GOLDEN_PROOF_JSON: &str = r#"{"circuit_proof":[152,112,127,104,136,15,6,147,49,133,180,95,235,55,161,92,74,72,221,214,81,123,131,201,16,65,220,215,2,210,129,186,61,172,215,128,238,166,176,13,79,96,6,195,188,148,28,32,172,186,145,153,151,197,52,136,3,196,165,49,232,69,30,95,17,221,86,45,233,18,100,222,95,244,199,138,0,182,26,123,253,81,203,237,131,155,162,251,216,108,153,111,200,112,148,55,177,81,119,24,103,225,184,90,137,111,202,219,122,159,24,223,179,117,232,3,249,125,103,227,47,100,213,174,77,252,154,21,195,15,79,71,175,14,151,86,169,170,85,134,165,63,78,228,150,1,101,153,123,26,181,211,8,209,13,148,239,179,212,150,42,174,78,241,250,113,26,173,17,250,250,42,122,69,160,199,226,187,109,77,36,8,124,83,241,154,191,24,117,131,148,67,153,164,60,217,98,51,255,1,6,140,208,218,247,145,112,172,110,191,52,254,159,197,181,42,236,141,42,106,202,211,232,75,232,185,2,16,67,115,14,239,134,151,83,219,92,150,60,243,146,255,29,200,55,244,173,127,154,23,14,30,7,122,21,0,152,197,66,16,88,249,229,221,177,176,210,228,146,33,43,64,213,203,23,149,50,150,55,147,45,126,86,192,214,196,222,120,147,255,156,171,205,155,36,62,209,160,101,241,62,252,76,36,107,172,5,129,138,144,121,146,139,220,84,147,62,221,101,42,9,146,197,92,117,126,61,246,131,106,36,244,113,187,30,195,182,20,170,252,241,33,133,253,207,6,38,206,43,147,174,81,142,64,84,43,145,232,207,187,185,20,188,77,161,227,142,215,242,204,147,19,215,202,110,20,167,6,249,20,71,174,84,10,153,40,44,159,219,212,174,239,36,16,46,183,200,26,225,69,174,54,163,23,154,188,233,185,239,51,233,216,127,64,115,216,233,157,6,36,120,153,230,212,15,108,178,158,196,7,191,87,185,51,168,43,39,49,221,96,224,1,21,238,34,135,129,166,87,23,190,36,50,128,122,218,190,228,70,87,75,78,72,108,233,53,81,65,199,222,232,175,94,239,241,122,143,140,71,142,133,251,152,156,81,141,77,84,86,129,170,165,42,245,58,15,158,171,214,76,147,9,161,83,61,187,246,221,150,170,142,214,104,142,225,253,217,123,251,74,169,168,61,157,158,205,83,215,183,18,49,212,202,107,37,107,80,163,208,242,116,251,35,111,28,22,27,169,163,169,13,93,200,136,170,58,68,71,85,0,43,24,87,14,53,239,72,253,142,201,228,20,239,192,210,37,182,85,193,135,175,205,249,135,59,210,131,21,156,131,247,17,161,229,68,179,33,220,65,22,239,137,176,174,168,245,120,37,214,163,161,198,192,204,4,188,116,41,252,179,251,26,201,255,150,17,146,99,198,30,194,25,113,16,48,87,11,110,182,39,239,52,10,125,250,2,3,27,244,147,185,179,44,119,189,35,141,97,151,17,116,75,90,175,200,25,166,169,196,112,138,203,140,27,93,47,236,54,26,68,66,179,226,52,81,19,2,27,191,75,171,139,19,46,193,42,134,204,64,216,254,133,24,206,233,242,218,95,6,169,177,132,243,113,120,157,159,229,100,116,140,94,197,215,67,47,242,186,57,1,82,25,100,231,183,155,33,164,72,15,33,88,231,113,119,2,56,14,68,225,7,68,103,22,12,136,177,59,78,61,135,127,97,72,162,199,141,78,129,215,240,210,17,119,225,80,77,171,236,224,210,148,165,244,119,23,121,98,81,144,194,109,53,33,93,52,85,5,183,42,44,115,44,232,62,226,201,80,49,200,216,188,194,169,200,110,134,58,47,88,143,20,105,40,79,221,100,10,211,243,157,224,205,44,21,181,204,173,155,155,132,121,89,129,103,213,45,253,192,76,143,252,51,130,81,66,205,130,4,229,196,24,89,56,140,143,53,110,84,248,205,50,20,67,93,172,138,137,115,216,86,51,201,154,183,84,56,131,66,216,97,36,141,151,124,149,181,146,160,131,170,67,45,53,8,62,192,174,36,255,50,16,174,251,64,147,77,40,106,59,184,6,202,118,139,244,134,216,173,152,49,205,242,24,222,120,164,236,189,72,231,146,14,101,228,242,105,147,51,145,109,25,164,123,193,93,105,99,121,139,147,28,56,58,116,77,122,149,9,143,86,11,94,130,157,134,73,209,85,124,106,126,241,164,243,97,78,65,199,86,110,143,249,194,184,218,16,146,48,40,196,234,245,217,88,41,91,185,181,35,140,66,238,146,57,47,35,84,24,123,135,52,111,47,185,85,45,22,176,216,206,56,175,2,12,50,50,63,124,179,207,126,241,168,5,8,179,243,94,53,26,97,57,115,93,70,147,145,136,21,162,208,227,213,186,35,29,22,223,55,98,128,210,174,122,92,234,40,164,163,125,133,154,244,148,37,80,83,230,55,17,4,5,166,70,198,173,46,207,21,92,212,116,144,133,7,142,114,242,16,174,244,171,94,103,99,224,72,247,157,246,225,52,236,159,229,201,239,70,165,49,140,97,151,50,139,249,243,18,44,50,90,226,169,104,129,208,214,173,80,71,233,138,96,30,214,135,152,73,57,30,33,35,246,34,55,88,127,64,48,146,153,157,119,146,91,220,100,136,197,225,140,158,48,144,4,68,151,4,50,234,100,149,245,190,49,191,204,189,82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,32,232,174,179,193,73,38,225,105,221,60,81,7,198,58,63,170,119,214,3,229,163,86,253,127,134,96,178,94,234,32,91,255,96,81,170,73,125,96,6,145,228,221,155,123,198,59,49,99,157,187,203,177,240,55,176,68,128,242,93,219,64,103,177,2,76,32,220,147,212,73,222,184,134,47,138,104,203,39,185,5,144,44,114,100,148,232,224,33,20,131,109,69,188,39,141,89,81,111,23,177,128,73,97,5,154,107,45,27,230,159,108,59,199,238,146,138,102,255,229,237,55,43,106,235,204,12,34,184,163,154,194,62,192,12,160,213,68,251,21,174,114,68,70,13,252,19,129,182,29,39,61,74,150,249,13,100,185,51,196,23,24,226,230,92,169,130,243,181,148,59,219,140,178,232,12,178,110,101,101,135,226,186,1,13,183,103,210,181,170,65,188,174,81,105,72,112,206,120,15,201,18,164,99,54,104,166,66,208,38,183,126,243,74,179,15,154,195,101,208,148,107,88,97,47,223,153,225,166,31,158,127,137,182,151,134,45,169,164,176,246,9,175,170,235,252,227,230,245,215,134,251,68,124,20,120,47,49,128,144,182,71,53,252,105,194,232,251,76,236,201,236,148,62,159,214,18,215,153,162,18,232,242,246,231,6,77,24,48,216,201,227,123,249,179,19,32,253,5,233,229,205,54,197,200,17,142,10,246,93,29,46,129,1,27,180,83,36,34,224,216,49,189,109,254,172,218,235,25,180,253,119,39,49,120,7,128,103,16,116,78,180,22,161,82,239,150,232,114,36,42,9,33,23,76,231,222,241,188,81,186,84,157,12,31,245,238,77,133,25,249,16,16,131,211,56,144,248,37,122,82,11,115,207,177,204,98,213,152,2,49,125,132,141,209,230,149,7,167,115,7,160,154,107,43,75,211,227,108,213,68,245,77,213,89,49,86,104,23,238,184,63,254,112,207,180,39,19,87,40,162,186,21,214,27,231,227,52,124,196,179,154,210,179,102,159,62,70,56,71,4,167,105,137,61,165,170,179,196,28,192,201,228,135,131,202,191,224,101,17,253,149,154,164,198,241,215,33,10,116,99,214,172,136,225,57,116,72,177,230,179,57,30,162,45,236,92,233,73,190,103,231,187,254,151,16,134,233,174,234,16,86,102,178,222,135,39,41,202,98,159,184,102,13,198,39,150,154,91,97,27,2,222,107,252,132,192,100,73,17,127,35,101,108,144,167,162,68,13,112,87,32,23,131,69,108,189,197,179,24,65,172,118,72,148,26,138,178,106,125,195,134,86,44,26,224,50,57,26,203,192,42,167,148,200,7,115,182,73,35,241,157,112,31,108,226,93,2,166,14,186,94,112,206,122,191,51,184,120,161,28,235,84,248,7,58,27,43,228,19,166,251,129,149,9,200,163,217,169,180,57,182,202,60,237,213,15,20,75,1,192,106,192,49,23,115,216,240,103,94,231,242,87,194,172,105,71,88,184,165,25,187,147,62,91,153,110,254,55,254,40,218,231,12,151,209,220,130,202,50,221,104,240,150,7,127,132,126,214,207,199,72,225,162,230,72,57,79,32,15,18,78,15,21,19,123,122,42,109,115,118,183,103,210,35,233,17,191,144,182,102,36,175,176,237,106,135,12,174,224,6,46,239,85,36,237,254,254,83,60,178,14,202,34,191,238,1,121,189,234,203,20,115,228,135,126,125,210,86,80,83,127,149,23,83,59,81,204,97,83,90,17,28,16,52,209,104,219,241,231,243,150,40,139,108,164,134,18,229,241,61,41,214,107,22,86,238,204,13,209,250,152,209,61,240,57,199,212,120,85,51,7,254,246,169,161,136,133,235,78,13,56,232,64,41,131,141,87,130,50,75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,143,24,221,221,167,135,67,182,127,39,95,141,99,21,142,8,31,207,130,32,64,20,65,105,250,162,198,95,171,218,103,99,77,171,245,65,47,44,152,55,47,31,80,17,181,49,231,208,180,88,93,149,148,9,130,155,225,165,194,155,223,94,49,108,194,155,196,105,62,100,10,156,19,50,68,90,54,89,128,219,35,121,220,4,42,45,27,226,58,116,110,153,193,5,149,67,0,21,131,213,162,205,175,217,241,122,56,176,156,141,205,239,114,189,218,137,209,225,227,67,238,0,81,149,109,104,226,27,209,216,76,119,141,46,55,42,214,73,169,169,245,91,161,32,231,2,158,156,2,0,106,88,185,58,130,40,65,231,8,50,118,76,150,235,28,91,11,86,235,24,13,237,113,5,133,5,206,123,113,156,229,220,168,32,77,221,99,51,56,205,100,78,119,238,23,113,190,60,17,99,18,162,144,91,55,201,176,99,95,230,76,21,6,146,49,211,228,13,29,141,59,159,127,92,175,103,158,85,190,124,241,119,254,193,159,43,124,18,17,147,45,192,202,198,51,169,121,155,63,231,253,179,169,200,86,28,57,25,105,236,167,101,132,194,145,19,84,0,234,179,107,177,131,191,152,221,166,68,0,214,202,128,98,78,232,140,153,19,146,182,158,63,147,191,100,232,139,201,159,46,175,76,223,179,7,113,254,66,143,96,72,81,106,74,45,82,24,206,192,108,147,195,56,13,89,79,212,199,78,221,201,193,20,29,218,64,209,82,40,223,226,78,163,219,136,0,219,197,143,157,1,106,170,83,189,215,82,104,188,63,16,165,149,108,234,138,61,147,138,170,186,229,192,158,97,186,26,193,89,247,255,130,138,93,6,147,100,16,212,153,135,95,63,231,131,143,120,36,167,184,14,175,129,149,104,213,0,11,160,250,25,66,127,91,64,5,206,56,6,175,24,176,27,43,201,203,234,170,189,10,240,55,108,141,167,72,15,196,95,57,206,67,236,49,75,96,55,60,210,17,164,39,173,252,242,14,75,79,177,155,236,253,77,202,115,48,177,17,35,254,14,147,131,111,92,205,223,229,218,24,240,30,38,42,4,169,178,71,239,236,100,53,149,17,62,188,186,169,49,24,52,81,242,0,109,45,167,191,67,102,188,100,255,208,251,230,198,212,243,209,205,42,218,140,199,12,166,7,171,123,136,237,72,45,73,21,232,97,209,55,132,224,238,113,119,128,63,197,184,60,127,232,86,222,22,120,71,55,212,178,63,8,21,218,195,7,56,194,65,225,204,29,96,202,206,79,56,61,75,73,244,44,44,186,156,167,51,247,14,73,181,135,146,192,23,42,208,252,9,209,123,204,23,102,70,161,232,26,217,251,232,138,32,190,39,0,124,80,200,212,165,183,157,163,250,181,169,231,52,58,100,132,177,157,26,235,12,156,133,75,35,94,52,227,22,10,2,94,34,114,48,29,58,44,102,96,66,224,242,108,101,70,215,172,145,25,237,128,171,121,233,114,181,23,28,132,210,12,46,112,8,101,62,100,183,91,169,6,157,191,119,88,93,6,58,27,104,66,154,224,134,196,242,80,195,78,204,25,89,217,252,246,227,12,29,240,149,234,10,113,238,13,111,221,132,196,21,228,102,111,46,243,111,137,252,23,222,27,65,71,163,240,62,177,210,30,231,37,34,222,61,151,214,162,180,37,196,238,173,49,52,135,39,66,153,255,208,7,240,196,67,237,44,228,110,175,61,4,114,177,61,0,187,59,225,110,143,231,75,178,63,11,167,64,110,39,207,178,170,94,194,145,129,65,43,86,246,187,24,56,114,209,224,233,9,44,236,225,179,74,241,13,112,239,220,56,153,166,33,218,123,1,10,10,162,253,0,111,183,47,241,12,160,217,47,169,135,125,47,220,228,91,0,17,241,244,209,214,125,225,176,157,253,1,191,122,119,87,51,197,26,63,61,205,75,0,112,121,51,23,77,191,141,188,159,125,218,118,216,70,228,77,72,135,21,74,146,235,224,215,61,76,205,198,190,10,232,150,190,78,175,246,92,52,244,136,107,90,16,184,17,134,81,171,207,217,101,79,77,229,74,9,54,241,236,217,94,164,132,20,27,211,240,249,76,219,143,84,170,158,208,185,9,163,141,207,14,104,178,79,105,38,159,126,168,109,141,98,84,22,253,101,0,255,215,222,189,206,128,75,9,215,73,10,252,146,209,89,73,179,1,5,199,163,191,93,133,56,139,226,40,136,24,129,182,42,110,133,238,40,199,42,208,167,235,174,15,116,15,47,31,63,9,83,48,170,174,188,163,105,82,221,38,22,134,42,130,62,20,89,18,242,43,251,92,79,166,112,89,230,179,54,100,191,75,68,215,144,46,221,212,37,175,213,41,72,8,182,152,125,33,16,125,241,66,246,182,188,219,36,168,82,228,234,209,0,128,105,149,186,211,37,238,112,173,101,134,188,238,133,31,192,219,222,216,129,43,209,228,17,165,15,176,95,110,179,17,156,134,25,222,220,154,7,71,170,4,26,157,229,1,188,177,57,13,208,164,69,166,232,118,49,46,82,57,80,244,229,182,87,96,84,224,107,79,235,53,129,5,23,252,136,33,112,123,207,87,62,26,95,85,253,199,222,56,87,16,149,20,147,133,197,202,22,53,21,93,172,109,205,76,195,87,231,83,242,134,77,79,209,165,195,119,202,114,178,136,62,149,172,189,213,97,45,151,96,100,247,233,177,147,127,85,210,106,106,211,16,253,190,119,236,25,125,193,203,196,203,82,182,113,127,113,91,157,192,189,7,94,126,119,111,50,182,140,131,167,106,224,82,192,113,181,214,7,164,25,103,49,233,245,57,209,206,20,235,178,60,10,111,150,88,27,220,189,59,67,52,32,149,96,14,248,59,160,81,246,114,231,72,147,155,33,196,210,151,11,61,6,211,129,179,199,177,15,123,135,82,16,61,151,48,40,230,179,45,120,84,105,111,132,221,121,42,105,41,117,70,100,19,238,40,57,172,46,253,242,170,164,204,120,246,101,158,62,112,11,246,222,12,230,6,177,121,128,195,9,18,178,101,188,62,76,72,195,233,211,183,254,8,134,1,228,242,116,250,103,141,133,224,59,69,235,56,119,211,12,59,119,50,93,225,1,195,245,110,11,191,139,34,101,75,129,5,21,59,134,219,135,111,158,83,22,39,146,38,92,24,146,220,77,151,14,35,57,80,180,217,33,248,219,12,205,2,185,191,1,114,241,28,204,27,5,172,206,26,161,242,9,107,93,49,210,33,77,120,252,97,194,87,214,16,245,201,85,115,150,112,163,54,12,139,106,161,86,71,180,236,155,81,92,32,194,230,197,103,178,102,237,151,250,134,233,203],"params":{"m":200,"k":3,"phi_f":0.8},"merkle_tree_depth":4}"#;

        const GOLDEN_SNARK_VERIFIER_DATA_JSON: &str = r#"{"certificate_circuit_verification_key":[2,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,2,13,2,0,0,0,3,13,22,0,0,0,8,147,213,198,190,247,245,9,225,206,199,60,28,198,147,5,240,139,193,162,119,160,9,167,148,79,188,95,219,85,12,39,73,119,169,87,97,245,53,251,24,166,4,163,188,87,33,228,18,48,20,1,214,201,5,59,124,84,60,205,136,108,30,154,13,223,176,186,5,65,186,66,221,11,247,115,92,71,138,219,209,25,23,45,224,133,151,121,189,34,254,229,164,25,14,39,18,155,95,78,136,200,85,51,130,39,22,77,49,73,56,136,4,62,97,11,96,99,65,7,31,245,96,140,53,65,242,0,159,215,138,193,184,30,24,128,235,245,22,43,164,157,234,136,7,156,42,160,232,131,107,161,250,255,200,1,68,239,141,151,191,19,242,15,4,153,153,31,88,134,29,119,208,156,133,101,27,58,19,169,86,1,42,131,64,140,84,242,47,85,115,132,14,167,64,6,248,218,38,147,15,164,188,240,44,143,39,78,206,245,191,43,142,48,217,27,78,158,222,7,185,136,71,101,95,18,179,85,220,82,149,222,106,172,44,27,251,15,99,242,19,206,24,101,29,189,75,155,0,253,151,142,63,241,2,200,168,134,41,135,52,58,212,226,139,211,71,235,91,33,12,230,76,24,178,137,36,216,58,175,27,157,205,44,200,74,225,100,17,207,67,142,80,248,137,228,170,187,105,118,236,180,40,182,178,51,47,36,227,70,123,223,221,250,88,120,61,79,205,250,68,21,53,84,3,209,104,219,212,123,1,120,204,216,228,57,21,165,187,79,15,214,78,60,172,49,140,1,134,109,232,53,190,173,176,229,195,0,50,84,73,68,222,218,3,162,9,70,250,237,43,106,31,242,70,124,30,84,4,8,187,121,126,91,18,7,166,27,157,50,43,200,123,14,230,217,180,9,170,227,108,160,97,92,108,211,96,33,208,60,87,74,186,99,187,124,53,113,224,170,236,168,235,214,232,133,12,87,72,199,49,83,8,96,97,224,117,74,25,190,55,88,90,165,129,148,169,30,165,34,4,17,251,75,202,87,88,184,155,174,188,20,251,33,134,129,9,50,110,24,73,61,197,248,79,129,155,173,30,159,10,189,72,23,69,226,254,35,102,182,82,90,83,205,62,105,253,111,53,100,247,47,179,183,254,35,108,170,247,91,163,34,61,83,121,64,215,208,195,212,18,36,177,175,78,134,125,58,20,188,231,159,172,22,210,229,159,54,71,120,205,61,181,5,224,220,223,193,127,45,185,32,49,21,98,1,32,71,19,173,192,250,196,98,198,94,182,112,191,164,41,94,206,123,41,127,5,75,124,128,22,217,0,38,116,113,12,60,241,154,187,99,121,94,43,47,32,138,52,17,151,9,92,117,229,150,65,158,248,252,3,84,16,212,28,249,50,120,251,31,208,27,62,190,1,59,34,5,49,132,250,212,145,51,82,101,106,26,48,40,233,144,36,34,241,47,246,118,6,227,141,34,236,255,118,88,218,212,130,95,212,75,146,204,217,135,234,202,4,155,188,188,18,155,240,116,93,81,18,159,113,233,51,169,45,207,156,145,115,244,187,28,140,255,244,229,2,21,42,199,3,42,226,205,205,74,244,198,13,249,236,223,215,24,181,182,36,55,20,37,23,7,54,32,199,109,17,121,121,63,72,35,239,119,89,137,49,201,174,180,234,211,232,32,77,129,128,178,21,198,240,254,19,160,186,55,12,39,35,248,113,198,78,111,43,141,75,135,22,243,106,147,106,161,70,227,124,179,179,114,177,201,28,149,46,188,72,167,246,82,171,84,172,17,98,26,90,244,40,88,50,65,66,35,47,229,169,194,30,100,75,228,5,7,241,86,4,183,239,242,45,75,187,7,41,245,34,50,102,244,124,124,73,231,85,142,20,62,133,21,5,42,100,144,7,224,94,192,147,1,151,24,195,85,219,0,221,127,222,101,81,143,44,57,25,253,127,199,69,240,1,91,200,9,173,81,171,222,4,152,96,150,171,16,147,14,68,79,66,40,138,197,109,142,153,138,26,67,129,226,58,154,42,129,77,213,63,10,45,67,150,156,1,107,209,186,183,134,10,172,166,80,249,239,220,169,209,130,154,222,26,237,13,88,180,212,18,140,103,244,215,152,78,139,141,1,152,54,176,205,1,198,90,201,114,40,193,49,73,195,7,193,144,180,64,41,152,248,140,194,128,197,56,214,116,221,134,135,171,25,213,68,28,98,161,95,233,210,54,48,73,20,186,36,48,114,214,60,108,196,39,218,253,20,206,54,134,108,5,71,109,124,50,215,68,96,145,187,155,213,187,46,79,17,80,63,126,40,49,223,106,84,90,54,56,33,243,201,177,208,62,197,237,71,110,234,56,251,109,25,233,110,64,138,61,182,2,236,153,116,152,97,240,173,163,72,234,18,111,237,140,203,203,103,235,98,21,123,115,34,162,253,210,80,220,117,222,80,117,64,38,246,27,214,180,101,29,236,206,137,121,208,238,126,10,0,213,123,106,239,235,216,208,229,115,110,234,90,206,48,208,108,50,252,127,185,233,219,174,215,104,169,107,253,65,19,77,39,204,246,9,35,159,74,60,3,130,120,154,12,56,200,14,49,4,138,211,182,101,184,89,22,150,202,60,133,17,221,144,172,97,134,190,235,73,179,41,60,224,110,120,28,113,227,226,217,164,208,135,221,222,26,114,95,222,5,93,24,228,251,17,184,164,145,226,18,189,107,240,58,234,143,105,193,93,165,248,231,190,109,110,64,46,63,225,138,157,132,244,10,145,52,172,217,54,132,124,41,193,46,65,74,217,203,1,99,85,120,11,201,46,28,186,216,72,132,123,23,131,51,140,213,222,213,178,208,141,163,3,103,104,186,229,240,140,33,128,191,11,224,20,181,117,172,91,93,252,221,251,64,121,85,181,12,72,195,0,225,224,209,158,141,207,77,78,86,152,75,80,11,14,81,198,121,99,9,21,236,71,79,140,225,254,100,104,110,70,254,82,5,166,26,19,195,234,182,130,100,204,177,226,128,99,90,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,230,121,210,211,184,33,162,114,202,170,155,42,244,62,18,127,218,190,87,189,93,85,81,210,250,45,37,86,203,167,43,211,253,229,148,15,15,77,24,38,199,94,188,69,93,50,134,22,28,68,229,37,68,45,241,169,163,137,15,87,144,59,231,107,24,252,169,201,164,13,243,19,77,110,155,140,154,157,80,216,126,112,254,73,4,63,48,191,20,160,125,142,8,86,174,3,142,12,230,36,129,86,95,199,221,124,0,199,50,83,1,103,188,141,62,186,34,4,134,171,169,190,146,208,74,248,160,135,253,24,192,33,28,197,222,198,178,97,227,14,232,201,7,7,50,90,44,3,102,111,118,174,5,30,40,174,231,120,66,215,52,174,149,132,33,45,196,134,191,51,186,129,194,109,12,147,144,150,1,224,139,208,0,22,49,211,69,7,86,120,207,2,125,158,107,250,87,230,33,47,235,175,103,168,108,110,42,155,189,74,192,128,34,165,65,119,72,145,111,27,173,163,161,178,21,232,173,193,34,70,228,9,214,106,179,207,57,110,37,17,215,219,140,244,45,229,136,241,66,74,159,25,188,123,158,54,94,194,239,150,234,216,250,162,0,245,85,182,26,143,155,192,249,200,55,124,221,155,81,194,159,178,141,223,36,84,242,6,31,15,129,105,102,170,96,51,68,124,13,21,103,1,56,255,190,199,172,175,37,255,97,39,190,19,254,230,57,249,105,114,51,172,133,156,84,211,153,224,188,73,215,6,102,168,203,9,156,176,192,225,117,29,168,219,205,140,201,31,231,43,246,206,171,181,3,64,215,103,90,110,97,199,1,218,144,225,208,65,61,41,125,123,202,164,95,73,138,11,95,60,51,33,70,11,79,233,148,93,17,45,26,252,223,176,249,210,70,163,105,177,35,175,38,202,235,218,61,138,220,182,106,125,85,181,114,145,117,152,60,17,139,210,177,122,210,32,197,218,72,151,154,9,218,241,43,124,124,253,197,99,107,252,120,230,129,77,190,129,93,180,10,115,61,239,85,63,20,202,103,9,69,203,67,240,0,19,252,183,65,74,188,4,134,247,143,230,185,16,174,7,165,38,122,28,246,120,3,35,41,209,197,104,172,63,250,249,49,193,246,73,100,196,229,221,174,6,190,196,15,104,163,173,109,49,33,141,53,6,44,150,12,88,243,58,95,1,71,1,169,112,163,115,5,227,26,229,173,68,184,77,171,168,70,219,37,60,61,77,58,200,217,40,78,238,99,136,191,239,72,222,147,4,179,185,11,22,182,127,77,155,229,143,109,159,44,18,94,165,180,30,171,64,37,149,232,170,252,86,30,126,173,103,157,86,164,115,10,124,129,55,51,101,108,160,143,20,14,31,103,165,5,11,234,246,91,50,101,13,85,232,57,100,183,24,114,48,207,218,175,148,133,212,4,22,148,66,102,189,147,69,87,232,192,64,196,174,232,169,156,6,216,73,78,81,150,187,111,111,248,52,98,126,157,46,36,132,222,120,57,33,22,22,207,113,45,162,159,36,94,114,42,207,241,10,35,162,32,246,217,254,230,201,138,186,93,235,203,181,91,108,44,210,251,10,114,172,70,191,167,28,59,201,195,153,25,99,3,139,227,15,11,142,98,146,198,19,88,125,218,146,172,55,80,52,73,147,30,192,135,4,1,184,211,252,128,201,149,37,153,217,22,67,199,21,162,138,102,221,105,103,105,126,241,254,57,123,240,13,219,29,203,221,193,9,22,191,145,134,193,232,148,166,51,247,104,5,106,204,102,231,11,92,86,26,61,177,194,72,189,249,32,228,63,95,22,49,206,140,104,171,101,239,40,153,190,3,228,81,195,139,216,59,141,143,60,252,155,47,136,58,70,184,164,86,209,175,34,248,12,246,129,17,212,214,168,153,12,107,145,36,58,65,90,108,231,92,90,13,92,214,192,35,194,20,236,255,72,68,91,100,119,241,13,150,161,72,107,23,107,179,220,238,12,49,208,152,72,62,114,202,45,251,0,75,64,41,170,126,35,167,29,9,46,218,253,170,195,53,236,117,0,12,235,134,13,2,148,100,162,220,244,94,167,114,62,253,116,129,3,53,90,102,200,88,0,204,207,134,10,138,235,250,171,60,249,180,104,37,223,8,70,163,139,173,180,91,98,32,9,15,61,71,149,230,124,98,112,49,237,113,212,70,153,233,208,214,245,40,5,57,119,67,77,170,166,205,174,103,227,41,95,100,137,72,230,102,59,245,246,221,157,5,78,3,123,31,218,12,178,247,185,211,36,158,78,118,4,190,4,132,131,107,231,189,67,181,152,196,105,136,78,232,155,7,39,188,112,113,39,78,118,229,95,106,86,26,96,178,92,21,83,164,218,209,98,11,29,12,35,94,159,206,216,5,246,122,213,201,177,86,166,223,167,106,87,204,244,252,95,138,39,192,80,188,161,209,95,155,231,48,231,91,138,16,36,36,135,10,90,108,90,160,209,4,141,214,22,250,165,107,229,251,209,202,7,217,240,69,21,248,229,13,216,216,161,222,169,99,29,34,81,70,250,23,99,138,166,177,248,87,214,223,103,244,242,40,45,110,11,65,182,13,88,205,147,215,161,119,57,71,224,79,226,242,98,166,197,229,103,20,241,67,98,143,3,191,35,22,184,236,88,80,69,119,109,195,138,115,158,168,166,215,223,221,78,15,137,145,46,17,48,40,59,144,164,15,90,165,221,186,172,10,185,71,140,159,142,149,31,255,184,225,229,13,129,148,122,24,246,135,242,187,43,6,225,239,111,117,111,186,98,222,89,66,165,179,66,0,152,111,114,21,169,181,228,188,105,96,138,202,235,117,92,192,237,77,215,189,136,151,109,160,126,156,71,117,111,28,155,144,239,73,76,92,195,3,26,198,201,181,87,15,229,196,93,3,101,129,128,254,10,195,171,33,115,1,204,52,210,249,170,4,177,154,59,231,21,74,212,61,23,55,253,22,104,120,58,112,105,100,141,251,36,222,131,166,177,61,114,97,0,16,50,13,170,57,231,14,224,222,197,221,9,72,57,236,142,145,172,223,34,16,130,115,160,141,247,87,142,41,253,115,246,197,226,81,181,245,92,134,240,119,12,14,90,42,96,79,199,91,142,25,79,136,157,97,93,235,14,72,179,167,117,64,142,99,186,188,91,94,24,135,82,81,222,205,63,93,104,161,55,65,144,194,85,140,40,203,134,96,115,157,70,251,199,87,14,175,218,16,86,169,33,113,164,209,204,40,69,210,49,61,29,244,55,124,45,41,228,110,60,177,17,46,104,63,132,218,12,183,206,175,24,72,91,240,226,152,47,167,157,238,218,148,184,194,124,6,180,157,46,65,244,201,246,224,203,169,7,162,28,32,184,24,223,248,96,96,255,191,91,36,139,208,189,210,137,159,166,237,152,149,185,69,32,200,235,25,157,96,115,70,170,93,200,24,216,192,57,107,217,146,72,111,230,100,194,71,132,31,49,175,92,246,36,251,82,202,132,127,126,77,236,216,121,237,203,212,181,239,144,219,174,182,24,102,155,172,126,149,26,203,61,1,61,54,22,68,92,247,140,106,159,169,189,74,172,58,239,90,142,107,18,227,163,129,180,253,68,99,82,11,140,37,74,143,146,173,136,173,148,208,82,135,42,98,41,248,134,45,184]}"#;

        fn golden_snark_aggregate_verification_key_and_message() -> (
            AggregateVerificationKeyForSnark<MithrilMembershipDigest>,
            [u8; 32],
        ) {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let params = Parameters {
                m: 200,
                k: 3,
                phi_f: 0.8,
            };
            let (_, clerk) = setup_signers_and_clerk(params, 10, &mut rng);
            (
                clerk.compute_aggregate_verification_key_for_snark(),
                [1u8; 32],
            )
        }

        fn golden_combined_aggregate_verification_key_and_message()
        -> (AggregateVerificationKey<MithrilMembershipDigest>, [u8; 32]) {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let params = Parameters {
                m: 200,
                k: 3,
                phi_f: 0.8,
            };
            let (signers, _) = setup_signers_and_clerk(params, 10, &mut rng);
            (
                Clerk::new_clerk_from_signer(&signers[0]).compute_aggregate_verification_key(),
                [1u8; 32],
            )
        }

        #[test]
        #[ignore]
        fn generate_golden_values() {
            let params = Parameters {
                m: 200,
                k: 3,
                phi_f: 0.8,
            };
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let (signers, clerk) = setup_signers_and_clerk(params, 10, &mut rng);
            let message = vec![1u8; 32];
            let signatures: Vec<SingleSignature> =
                signers.into_iter().map(|s| s.sign(&message).unwrap()).collect();
            let setup = SnarkProverSetup::try_new(
                &params,
                MERKLE_TREE_DEPTH_FOR_SNARK,
                &TrustedSetupProvider::default(),
            )
            .unwrap();
            let mut prover = SnarkProver::new_non_deterministic(Arc::new(setup));

            let proof: SnarkProof<MithrilMembershipDigest> =
                prover.aggregate_signatures(&clerk, &signatures, &message).unwrap();

            println!("proof value: {:?}", serde_json::to_string(&proof));
            println!(
                "verifier data: {:?}",
                serde_json::to_string(&snark_verifier_data_non_deterministic(&prover))
            );
        }

        fn golden_proof() -> SnarkProof<MithrilMembershipDigest> {
            serde_json::from_str(GOLDEN_PROOF_JSON)
                .expect("golden proof JSON deserialization should not fail")
        }

        fn golden_snark_verifier_data() -> SnarkVerifierData {
            serde_json::from_str(GOLDEN_SNARK_VERIFIER_DATA_JSON)
                .expect("golden verifier data JSON deserialization should not fail")
        }

        #[test]
        fn golden_conversion() {
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();
            assert!(
                golden_proof()
                    .verify(
                        &message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_ok()
            );
        }

        #[test]
        fn verify_fails_with_random_bytes_or_wrong_number_bytes() {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();
            let golden = golden_proof();

            let mut random_bytes = vec![0u8; golden.circuit_proof.len()];
            rng.fill_bytes(&mut random_bytes);
            let random_proof =
                SnarkProof::new(random_bytes, golden.params, golden.merkle_tree_depth);
            assert!(
                random_proof
                    .verify(
                        &message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_err(),
                "Verification of random proof should fail"
            );

            let not_enough_bytes = &golden.circuit_proof[0..golden.circuit_proof.len() - 1];
            let small_proof = SnarkProof::new(
                not_enough_bytes.to_vec(),
                golden.params,
                golden.merkle_tree_depth,
            );
            assert!(
                small_proof
                    .verify(
                        &message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_err(),
                "Verification of small proof should fail"
            );

            let mut too_many_bytes = golden.circuit_proof.to_vec();
            too_many_bytes.push(0u8);
            let large_proof =
                SnarkProof::new(too_many_bytes, golden.params, golden.merkle_tree_depth);
            assert!(
                large_proof
                    .verify(
                        &message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_err(),
                "Verification of large proof should fail"
            );
        }

        #[test]
        fn verify_fails_with_wrong_message() {
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let wrong_message = [2u8; 32];
            assert_ne!(message, wrong_message);
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();

            assert!(
                golden_proof()
                    .verify(
                        &wrong_message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_err()
            );
        }

        #[test]
        fn verify_fails_with_message_offset_by_the_field_modulus() {
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let modulus = BigUint::from_str_radix(&JubjubBase::MODULUS[2..], 16).unwrap();
            let offset_message_value = BigUint::from_bytes_le(&message) + modulus;
            let mut offset_message = [0u8; 32];
            offset_message.copy_from_slice(&offset_message_value.to_bytes_le());
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();

            assert!(
                golden_proof()
                    .verify(
                        &offset_message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_err()
            );
        }

        #[test]
        fn verify_fails_with_wrong_circuit_verification_key() {
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();
            // The production key is derived for a different circuit configuration, so it
            // genuinely gates verification of a proof produced by the test configuration.
            let production_verification_key = NonRecursiveCircuitVerifyingKey::try_from_bytes(
                NON_RECURSIVE_CIRCUIT_VERIFICATION_KEY_FOR_PRODUCTION,
            )
            .expect("the embedded production verifying key should deserialize");

            assert!(
                golden_proof()
                    .verify(
                        &message,
                        &avk,
                        &SnarkVerifierData::new(production_verification_key),
                        &verifier_setup.verifier_params,
                    )
                    .is_err(),
                "verification with a wrong circuit verification key must fail"
            );
        }

        #[test]
        fn valid_proof_prepares_and_checks() {
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();
            let verifier_data = golden_snark_verifier_data();

            let dual_msm = golden_proof()
                .prepare_and_check(
                    &message,
                    &avk,
                    verifier_data.certificate_circuit_verification_key(),
                    &verifier_setup.verifier_params,
                )
                .expect("prepare_and_check should succeed on a valid proof");

            // The returned DualMSM must still satisfy its own pairing check;
            // confirms the caller can reuse it (e.g. wrap into a cert accumulator).
            assert!(dual_msm.check(&verifier_setup.verifier_params));
        }

        #[test]
        fn prepare_and_check_fails_with_wrong_message() {
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let wrong_message = [2u8; 32];
            assert_ne!(message, wrong_message);
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();
            let verifier_data = golden_snark_verifier_data();

            golden_proof()
                .prepare_and_check(
                    &wrong_message,
                    &avk,
                    verifier_data.certificate_circuit_verification_key(),
                    &verifier_setup.verifier_params,
                )
                .expect_err("prepare_and_check should fail");
        }

        #[test]
        fn prepare_and_check_fails_with_random_bytes() {
            let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();
            let verifier_data = golden_snark_verifier_data();
            let golden = golden_proof();

            let mut random_bytes = vec![0u8; golden.circuit_proof.len()];
            rng.fill_bytes(&mut random_bytes);
            let random_proof =
                SnarkProof::new(random_bytes, golden.params, golden.merkle_tree_depth);

            random_proof
                .prepare_and_check(
                    &message,
                    &avk,
                    verifier_data.certificate_circuit_verification_key(),
                    &verifier_setup.verifier_params,
                )
                .expect_err("prepare_and_check should fail");
        }

        #[test]
        fn snark_proof_to_from_bytes() {
            let (avk, message) = golden_snark_aggregate_verification_key_and_message();
            let verifier_setup = SnarkVerifierSetup::try_new().unwrap();
            let golden = golden_proof();

            assert!(
                golden
                    .verify(
                        &message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_ok()
            );

            let proof_bytes = golden.to_bytes().unwrap();
            let reconstructed_proof: SnarkProof<MithrilMembershipDigest> =
                SnarkProof::from_bytes(&proof_bytes).unwrap();

            assert_eq!(
                proof_bytes,
                reconstructed_proof.to_bytes().unwrap(),
                "The original bytes should match the ones of the reconstructed proof."
            );

            assert!(
                reconstructed_proof
                    .verify(
                        &message,
                        &avk,
                        &golden_snark_verifier_data(),
                        &verifier_setup.verifier_params,
                    )
                    .is_ok()
            );
        }

        #[test]
        fn golden_aggregate_signature_verifies_with_ancillary() {
            let (avk, message) = golden_combined_aggregate_verification_key_and_message();
            let params = Parameters {
                m: 200,
                k: 3,
                phi_f: 0.8,
            };
            let aggregate =
                AggregateSignature::<MithrilMembershipDigest>::Snark(Box::new(golden_proof()));
            let ancillary = AncillaryVerifierData::Snark(golden_snark_verifier_data());
            aggregate
                .verify(&message, &avk, &params, Some(ancillary), None)
                .expect("golden Snark aggregate signature must verify via ancillary verifier data");
        }
    }
}
