name: Nightly Dispatcher

on:
  workflow_dispatch:
  # Important note about scheduled workflows:
  # Notifications for scheduled workflows are sent to the user who last modified the cron syntax in the workflow file.
  schedule:
    - cron: "0 1 * * *"

jobs:
  backward-compatibility:
    uses: ./.github/workflows/backward-compatibility.yml

  aggregator-stress-test:
    uses: ./.github/workflows/aggregator-stress-test.yml

  test-rust:
    uses: ./.github/workflows/test-rust.yml
    with:
      include-slow-tests: true
      never-save-cache: true

  test-client:
    uses: ./.github/workflows/test-client.yml

  test-e2e:
    uses: ./.github/workflows/test-e2e.yml

  publish-crate-dry-run-with-verification:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Publish package to crates.io
        uses: ./.github/workflows/actions/publish-rust-crates
        with:
          dry_run: "true"
          dry_run_verify: "true"
          packages: mithril-stm, mithril-build-script, mithril-common, mithril-aggregator-client, mithril-aggregator-discovery, mithril-cardano-node-internal-database, mithril-client, mithril-merkle-tree

  clippy-check-all-crates:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run clippy check on all crates
        shell: bash
        run: |
          ./.github/workflows/scripts/clippy-check.sh

  clippy-check-all-crates-all-features:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run clippy check on all crates with all features combinations
        shell: bash
        run: |
          ./.github/workflows/scripts/clippy-check-all-features.sh

  notify-on-failure:
    uses: ./.github/workflows/test-notify-on-failure.yml
    needs:
      [
        backward-compatibility,
        aggregator-stress-test,
        test-client,
        test-rust,
        test-e2e,
        publish-crate-dry-run-with-verification,
        clippy-check-all-crates,
        clippy-check-all-crates-all-features,
      ]
    if: failure()
    secrets: inherit
